version: "3"

services:
  postgres:
    container_name: postgres
    image: postgres:13.3
    environment:
      POSTGRES_USER: 'test-user'
      POSTGRES_PASSWORD: 'test-password'
      POSTGRES_DB: "shop-database"
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: always

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_DATABASE: 'shop-database'
      MYSQL_USER: 'test-user'
      MYSQL_PASSWORD: 'test-password'
      MYSQL_ROOT_PASSWORD: 'test-password'
    volumes:
      - mysql:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"

volumes:
    postgres:
    mysql:
